Repository RentDynamics/ng-core, pull requests merged in 2018-03, with the labels that each got.

#5 fix(testing folder): Updated the testing objects
  src/lib/shared/shared/auth.service.ts
  src/testing/auth-service.mock.ts
  src/testing/core-api-service.mock.ts
Labels: LGTM, merge-ready

#6 docs(CODE_REVIEWS.md): added new guidlines based on material2
  CODE_REVIEWS.md
  CONTRIBUTING.md
  package.json
Labels: LGTM, docs, merge-ready

#8 fix(package.json): enhanced peerDependencies, upgraded @angular to th…
  package-lock.json
  package.json
  yarn.lock
Labels: LGTM, fix, merge-ready
