Repository RentDynamics/ng-core, pull requests merged in 2018-09, with the labels that each got.

#23 @angular/cli build system integration
  .circleci/config.yml
  .gitignore
  .gulpfile.js
  .karma.conf.js
  .rollup.config.js
  .travis.yml
  README.md
  angular.json
  build.sh
  karma.conf.js
  ng-package.json
  ng-package.prod.json
  package-lock.json
  package.dist.json
  package.json
  src/browser-test-shim.ts
  src/lib/shared/api-old/api-old-auth-service-config.ts
  src/lib/shared/api-old/api-old-auth.service.ts
  src/lib/shared/api-old/api-old.module.ts
  src/lib/shared/api-old/index.ts
  src/lib/shared/core-auth.service.ts
  src/lib/shared/index.ts
  src/lib/shared/reporting/index.ts
  src/lib/shared/shared/auth.service.ts
  src/lib/tsconfig.es5.json
  src/lib/tsconfig.lib.json
  src/lib/tsconfig.spec.json
  src/public_api.ts
  src/test.ts
  src/typings.d.ts
  test.sh
  tsconfig-spec.json
  tsconfig-spec.upgrade.json
  tsconfig.json
  tsconfig.lib.json
  tsconfig.spec.json
  tsconfig.upgrade.json
  tslint.json
Labels: BREAKING_CHANGE, LGTM, enhancement, merge-ready

#24 Fix @rd/core/testing
  src/lib/shared/api-old/api-old-auth.service.spec.ts
  src/testing/index.ts
  testing/auth-service.mock.ts
  testing/core-api-service.mock.ts
  testing/index.ts
  testing/package.json
  tsconfig.json
Labels: LGTM, bug-fix, merge-ready

#27 Circular reference warning fix (--aot mode)
  .circleci/config.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
  angular.json
  package-lock.json
  package.dist.json
  package.json
  src/lib/shared/api-old/api-old-auth-service-config.ts
  src/test.ts
  tsconfig.json
  tslint.json
  yarn.lock
Labels: LGTM, bug-fix, merge-ready

#30 feat(AuthService): Updated the AuthService to use window.localStorage
  .circleci/config.yml
  package-lock.json
  package.json
  src/lib/shared/shared/auth.service.ts
Labels: BREAKING_CHANGE, LGTM, enhancement

#31 Logout fix
  src/lib/auth/core-auth-routing.module.ts
  src/lib/auth/core-auth.module.ts
  src/lib/auth/core-logout/core-logout.component.css
  src/lib/auth/core-logout/core-logout.component.html
  src/lib/auth/core-logout/core-logout.component.spec.ts
  src/lib/auth/core-logout/core-logout.component.ts
  src/lib/auth/core-logout/core-logout.resolve.ts
  src/lib/auth/guard/auth.guard.ts
  src/lib/auth/index.ts
  src/lib/auth/logout/logout.component.spec.ts
  src/lib/auth/logout/logout.component.ts
Labels: LGTM, bug-fix, merge-ready

#32 Logout fix fix
  src/lib/auth/core-auth.module.ts
  src/lib/auth/core-logout/core-logout.component.html
Labels: LGTM, bug-fix

#33 fix(core-logout.component.ts): changed its onInit navigation from nav…
  src/lib/auth/core-logout/core-logout.component.ts
Labels: LGTM, bug-fix
